export const GAME_CONFIG = {
  width: 720,
  height: 420,
  totalTimeSeconds: 70,
  playerSpeed: 380,
  playerWidth: 64,
  playerHeight: 18,
  starRadius: 9,
  bombRadius: 11,
  powerUpRadius: 10,
  starSpawnInterval: 550,
  bombSpawnInterval: 1500,
  powerUpSpawnInterval: 8000,
  fallSpeedMin: 120,
  fallSpeedMax: 260,
  maxLives: 4,
  shieldDurationSeconds: 6,
  bossLevelStep: 4,
  bossWaveDurationSeconds: 16,
  bossHitsToClear: 3,
  specialCooldownSeconds: 11,
  maxLevel: 10,
};
